//* This file is part of the MOOSE framework
//* https://www.mooseframework.org
//*
//* All rights reserved, see COPYRIGHT for full restrictions
//* https://github.com/idaholab/moose/blob/master/COPYRIGHT
//*
//* Licensed under LGPL 2.1, please see LICENSE for details
//* https://www.gnu.org/licenses/lgpl-2.1.html
#include "InterfaceReaction1TestApp.h"
#include "InterfaceReaction1App.h"
#include "Moose.h"
#include "AppFactory.h"
#include "MooseSyntax.h"

template <>
InputParameters
validParams<InterfaceReaction1TestApp>()
{
  InputParameters params = validParams<InterfaceReaction1App>();
  return params;
}

InterfaceReaction1TestApp::InterfaceReaction1TestApp(InputParameters parameters) : MooseApp(parameters)
{
  InterfaceReaction1TestApp::registerAll(
      _factory, _action_factory, _syntax, getParam<bool>("allow_test_objects"));
}

InterfaceReaction1TestApp::~InterfaceReaction1TestApp() {}

void
InterfaceReaction1TestApp::registerAll(Factory & f, ActionFactory & af, Syntax & s, bool use_test_objs)
{
  InterfaceReaction1App::registerAll(f, af, s);
  if (use_test_objs)
  {
    Registry::registerObjectsTo(f, {"InterfaceReaction1TestApp"});
    Registry::registerActionsTo(af, {"InterfaceReaction1TestApp"});
  }
}

void
InterfaceReaction1TestApp::registerApps()
{
  registerApp(InterfaceReaction1App);
  registerApp(InterfaceReaction1TestApp);
}

/***************************************************************************************************
 *********************** Dynamic Library Entry Points - DO NOT MODIFY ******************************
 **************************************************************************************************/
// External entry point for dynamic application loading
extern "C" void
InterfaceReaction1TestApp__registerAll(Factory & f, ActionFactory & af, Syntax & s)
{
  InterfaceReaction1TestApp::registerAll(f, af, s);
}
extern "C" void
InterfaceReaction1TestApp__registerApps()
{
  InterfaceReaction1TestApp::registerApps();
}
